blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/shallow1992/obsidian-format-convert-copy/discussions
    about: Ask questions or discuss ideas with the community.
